language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
  - >-
    npm run update-types && git diff --exit-code || (echo -e
    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
    update-types".' && false)
env:
  global:
    - secure: >-
        TLPp/SYuGujw5miaEw8cTsM5VdDwTRkUgpsAFsYEqx8dMfazmjMlmbmib2Zpdvsjk40gRxQlCF0zgNPAp/+LMArbbxYzJG4OfzwP4l9IfJlHsu1dmK6RhKfnbUyd7Al21ldcOawhxHLCaLTv8R21hpzT/8dGZboLotAC/NuzYyw=
    - secure: >-
        B3AVqFFsI8IRB7Xuy3L0m8a5t9M9Lm/rywwQPYGQZVv1IU/dLJUKQvFCrHTRoD2d0b5IuVhWqnzUpwFnWp/fSoCv26hy8kq3PwhZ4bxeoK7FLLz0qxqqQx5aHV0PlxXWomAUDF0n9QF+p/BBznvlmNWWnCegqmem37zvVK/lqTs=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
cache:
  directories:
    - node_modules
